# Change these first
owner: williamtran29
repo: lasxd578

sites:
  - name: Lasxd578
    url: https://lasxd578.vn/

status-website:
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Lasxd578"
  introMessage: Lasxd578 Status
